# Generated by Django 3.0.2 on 2020-05-25 09:23

import agenda.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(blank=True, upload_to='profile/')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True)),
                ('img_url', models.ImageField(blank=True, upload_to='organisations/')),
                ('banner_url', models.ImageField(blank=True, upload_to='organisations/banner/')),
                ('contact', models.CharField(max_length=25)),
                ('siteweb', models.CharField(blank=True, max_length=300)),
                ('facebook', models.CharField(blank=True, max_length=300)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(blank=True, max_length=500)),
                ('lieu', models.CharField(max_length=100)),
                ('horodage', models.DateTimeField()),
                ('affiche_url', models.ImageField(blank=True, upload_to=agenda.models.Event.upload)),
                ('organisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Organisation')),
                ('reservations', models.ManyToManyField(blank=True, to='agenda.Compte')),
            ],
        ),
        migrations.AddField(
            model_name='compte',
            name='suivies',
            field=models.ManyToManyField(blank=True, to='agenda.Organisation'),
        ),
        migrations.AddField(
            model_name='compte',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
