# Generated by Django 3.0.2 on 2020-05-24 12:32

import agenda.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('pseudonyme', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('img_url', models.ImageField(blank=True, upload_to='profile/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('identifiant', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=300)),
                ('info', models.TextField(blank=True)),
                ('img_url', models.ImageField(blank=True, upload_to='organisations/')),
                ('banner_url', models.ImageField(blank=True, upload_to='organisations/banner/')),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(blank=True, max_length=500)),
                ('lieu', models.CharField(max_length=100)),
                ('horodage', models.DateTimeField()),
                ('affiche_url', models.ImageField(blank=True, upload_to=agenda.models.Event.upload)),
                ('organisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Organisation')),
                ('reservations', models.ManyToManyField(blank=True, to='agenda.Compte')),
            ],
        ),
        migrations.AddField(
            model_name='compte',
            name='suivies',
            field=models.ManyToManyField(blank=True, to='agenda.Organisation'),
        ),
    ]
